### ISSUE TITLE
Test Connection Ideas

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Coincidence_System#11]
In 80bb6f363ae83df64f803ba054f8534768df96ef I added a part where it checks if `"test-connection"` is passed in the `'_id'` field of an observation message. 
I (stupidly) was printing it on the server, thinking that this would be a confirmation message. However, of course, this is printed on the server terminal. Thus, the user still won't know if their messages are received by the server.

We need to feed this back to the user, without having private channels, the only option I see is publishing a message in the observation(?) topic saying that;
`2022-04-14 15:45 connection test message is received from 'TEST'`, the user would still be required to launch a second terminal and subscribe to something...

Alternative, and maybe unnecessarily sophisticated solution would be;

- user submits a message via a function called `test_connection()`
- `test_connection()` generates a hash and publishes `{'_id' : 'test-connection', ''hash':'xsASgwe35s'}`
- `test_connection()` subscribes to a  _special test channel_ and listens
- on server `run_coincidence` receives `{'_id' : 'test-connection', 'hash':'xsASgwe35s'}` and submits a message to this channel with this specific hash
- `test_connection()` receives messages (possibly more than one, if there are also others testing) but it compares this hash
- if there is a `hash_sent == hash_read` match, it confirms that the message is received by the server.

is this an overkill? :D

**Comment by KaraMelih** [comment]
@Storreslara @joesmolsky ideas on this?

**Comment by KaraMelih** [comment]
well, I see that a timestamp would do the trick, no need for hash actually. If we have enough precision on the timestamp it should work.

**Comment by Storreslara** [comment]
agree just a time stamp in UTC would be enough

**Comment by KaraMelih** [comment]
Let's do this; "record the timestamp, check the stream, if the message with your timestamp is received, display 'confirmed'" idea also on the observation messages. (as suggested in https://github.com/SNEWS2/SNEWS_Publishing_Tools/issues/38)

**Comment by KaraMelih** [comment]
Hmm, reading your previous comment, I see that we could indeed also send a confirmation after the user sends an observation message. <br>
While this can be added, do we really need it? Is it sufficient for the user to test their connection using `test-connection` function, or would the user also wants to get that confirmation after they submit the observation message
