### ISSUE TITLE
Unit Tests CI/CD integrations

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Coincidence_System#113]
To keep track of this, I created an issue.

We need unit tests and automated github actions. <br>
Afet implementing the data models, the tests should be easy to implement. As for the github actions, one of them might/should be creating requirement.txt from the poetry requirements at each PR to make sure they are synchronized

**Comment by sybenzvi** [comment]
I have created a GitHub action that runs the unit tests and created one dummy test that just tests module initialization. The `install` and `pytest` commands are both called using `poetry` to ensure the environment is correct.

The only wrinkle is that automated tests with Python 3.12 are not working; installation works fine but the buildbot complains that
```
import six.moves
```
is failing. I cannot reproduce this offline.
