### ISSUE TITLE
alert message content

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Coincidence_System#2]
https://github.com/SNEWS2/SNEWS_Coincidence_System/blob/aee4c9408c2bd6ff4a8d6f43948b00e340e3735c/snews_cs/snews_coinc_v2.py#L224

at this line, `ids` is expected to be a list of detector ids. Is there a reason we pass just a None or is it just not yet implemented? <br>
Also, do we only submit the involved detectors' ids and not their names? 
I think id-name pairing already exists in snews_pt so I don't see harm passing the detector name in the alert messages
@Storreslara @joesmolsky

**Comment by Storreslara** [comment]
fixed in new commit, thanks
