### ISSUE TITLE
Change time format to ISO

### ISSUE THREAD

**Issue by joesmolsky** [SNEWS2/SNEWS_Coincidence_System#30]
Timestamps and datetime objects should be in ISO format.

Most of the work seems to me changing how variables are assigned.

Current method example
```python
# Current time
t = datetime.utcnow().strftime("%y/%m/%d %H:%M:%S:%f")

# Converting strings
 nu_t = self.times.str_to_datetime(message['neutrino_time'], fmt='%y/%m/%d %H:%M:%S:%f')
       
```

New method example
```python
# Current time
t = datetime.utcnow().isoformat()

# Converting strings
 nu_t = datetime.fromisoformat(message['neutrino_time'])
```

This makes TimeStuff() unneeded.

I've started the `iso-time` branch for this issue.

**Comment by habig** [comment]
I think this one's all done?  Certainly there's a lot of ISOs around.  What's left to do?

**Comment by joesmolsky** [comment]
I think it's done too.  We can reopen it if needed.
