### ISSUE TITLE
Single detector update triggers alert

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Coincidence_System#73]
When the same detector updates its own message it triggers an "update-alert" even if the first message is not in coincidence with any other detectors.

```
snews_pt run-scenarios
```
then select the 5th option "same detector submits within 1sec" and watch the alerts.

Probably need a check within update alert function before triggering the alert

**Comment by KaraMelih** [comment]
So does with the 4th scenario "same message submitted twice" <br>
Where the exact same message is submitted by the same detector

**Comment by justinvasel** [comment]
I was able to replicate this behavior.

The problem area seems to be `snews_coinc.py:add_to_cache`, which determines whether a new message represents an update based on whether its detector is already in the cache sub-group.

A solution to the "same message submitted twice" bug isn't too tough; you can just check that the relevant properties of the message and the cache record are equivalent, and then ignore the message. For example:
```python
    def add_to_cache(self, message):
        """
        Takes in SNEWS message and checks if it is a retraction, update or new addition to cache.
        This is the 'core' function of CoincidenceDataHandler
        Parameters
        ----------
        message : dict
            SNEWS Message, must be PT valid

        """
       # Assume these are the "important" attributes that uniquely define an experiment detection event
       # If any of these attributes differ from the cache, it's probably updated information.
        message_primary_keys = ['detector_name', 'neutrino_time', 'p_val', 'meta']

       # Check for duplicate messages by querying cache entries that match the message attributes.
        duplicate_messages = self.cache[
            np.logical_and.reduce(
                [message.get(k) == v for k, v in self.cache.get(message_primary_keys).items()])
        ]
        is_message_duplicate = len(duplicate_messages) > 0

        is_message_retraction = 'retract_latest' in message.keys()
        is_detector_in_cache = message['detector_name'] in self.cache['detector_name'].to_list()
        is_message_update = is_detector_in_cache and not is_message_duplicate

        # retraction
        if is_message_retraction:
            print('RETRACTING MESSAGE FROM')
            self.cache_retraction(retraction_message=message)
            return None  # break if message is meant for retraction
        message['neutrino_time_as_datetime'] = datetime.fromisoformat(message['neutrino_time'])

        # duplicate
        if is_message_duplicate:
            print('MESSAGE IS A DUPLICATE. IGNORING...')
            return None

        # update
        if is_message_update:
            print('MESSAGE IS AN UPDATE')
            self._update_message(message)
            return None

        # regular add
        self._manage_cache(message)
        self.cache = self.cache.sort_values(by=['sub_group', 'neutrino_time_delta'], ignore_index=True)
        self.cache = self.cache.reset_index(drop=True)
        return None
```

But what about the other case, when a detector sends another message with a different neutrino time within the coincidence window, but all other properties are the same? 

Does that truly count as two distinct message? 
- If not, then should the second message be disregarded? Should the cache record be updated with the neutrino time from the new message, but without triggering an UPDATE alert? 
- If so, then under the current logic, a single detector can be coincident with itself and trigger an alert.

Either way, there are probably a couple constraints that we want to enforce:
1. An UPDATE alert can only be issued if a regular alert has already been issued
2. The minimum number of detectors required for coincidence is 2
3. A duplicate message (i.e., all "important" details are equivalent) should not be added to the cache as a separate detection.

**Comment by KaraMelih** [comment]
Thanks for checking! I agree, we should definitely enforce that an update message is sent only if a regular alert is issued. <br>
Regarding which one of the two messages from a detector to take: I think we said if they are more than `min_time_window` apart, we keep both and open new coincidence sub groups/windows. However, if the messages are close, my naive intuition is that something triggered the DAQ several times and it kept sending messages so we should take the earliest neutrino time. However, it can also happen that they improved their analysis and now providing a more accurate neutrino time, and it turns out to be a later time than the first. <br>
So, I think the decision of which one to discard and which one to take is up to the collaboration. <br>

We can also check if either coincides with another detector and take that one to be more pragmatic. But that requires the repeating messages come _after_ there is already a message from another detector.

**Comment by Storreslara** [comment]
https://github.com/SNEWS2/SNEWS_Coincidence_System/pull/78

**Comment by Storreslara** [comment]
Confirmed that new logic fix does not publish an alert when a single message is updated, Firedrill 12/15/23
