### ISSUE TITLE
Out of order coincidence

### ISSUE THREAD

**Issue by KaraMelih** [SNEWS2/SNEWS_Coincidence_System#74]
In #69 the "out of order" scenario does not trigger an alert for an unknown reason.

I tested with the current branch and the scenario "3 messages, out of order" works as expected.<br> 
In this scenario we first receive a message from 
 - DUNE at 12:34:55
 - DS-20k at 12:34:47
 - XENONnT at 12:34:45

and it should still trigger an alert, first after the DS-20k saying DUNE+DS-20k formed a coincident, and then an update-alert saying all three formed a coincidence. <br>

While this works with the main branch, it stopped working with the #69 although there is no obvious relation. We need to check what changed.

**Comment by justinvasel** [comment]
I was able to replicate this bug in my local environment, but I also saw it for the main branch. 

See #76 for more details.

**Comment by KaraMelih** [comment]
Thanks Justin! I was also aware of this part and I think Sebastian was working on it too. <br>
The curious thing is that it still worked for me in the main branch although this part is unchanged in the PRs.
Nonetheless, thanks for the fix! I think we can safely merge this one first.
